// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"english_checkin_backend/internal/handler"
	"english_checkin_backend/internal/job"
	"english_checkin_backend/internal/repository"
	"english_checkin_backend/internal/server"
	"english_checkin_backend/internal/service"
	"english_checkin_backend/pkg/app"
	"english_checkin_backend/pkg/jwt"
	"english_checkin_backend/pkg/log"
	"english_checkin_backend/pkg/server/http"
	"english_checkin_backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	db := repository.NewDB(viperViper, logger)
	syncedEnforcer := repository.NewCasbinEnforcer(viperViper, logger, db)
	handlerHandler := handler.NewHandler(logger)
	repositoryRepository := repository.NewRepository(logger, db, syncedEnforcer)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	adminRepository := repository.NewAdminRepository(repositoryRepository)
	adminService := service.NewAdminService(serviceService, adminRepository)
	adminHandler := handler.NewAdminHandler(handlerHandler, adminService)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	studentRepository := repository.NewStudentRepository(repositoryRepository)
	studentService := service.NewStudentService(serviceService, studentRepository)
	studentHandler := handler.NewStudentHandler(handlerHandler, studentService)
	studentProgressRepository := repository.NewStudentProgressRepository(repositoryRepository, db)
	studentProgressService := service.NewStudentProgressService(serviceService, studentProgressRepository)
	studentProgressHandler := handler.NewStudentProgressHandler(handlerHandler, studentProgressService)
	taskRepository := repository.NewTaskRepository(repositoryRepository, db)
	taskService := service.NewTaskService(serviceService, taskRepository)
	taskHandler := handler.NewTaskHandler(handlerHandler, taskService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, syncedEnforcer, adminHandler, userHandler, studentHandler, studentProgressHandler, taskHandler)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewCasbinEnforcer, repository.NewAdminRepository, repository.NewStudentRepository, repository.NewStudentProgressRepository, repository.NewTaskRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewAdminService, service.NewStudentService, service.NewStudentProgressService, service.NewTaskService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewAdminHandler, handler.NewStudentHandler, handler.NewStudentProgressHandler, handler.NewTaskHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
